server:
  port: 8761

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#  instance:
#    prefer-ip-address: true # <--- ADD THIS
#      # Alternatively, you can force it to use localhost:
#      # hostname: localhost