server:
  port: 8000

spring:
  application:
    name: aura-gateway
  cloud:
    gateway:
      routes:
        - id: credit_service_mcp
          uri: lb://CREDIT-SERVICE  # <-- Dynamic lookup via Eureka!
          predicates:
            - Path=/credit/mcp/**
          filters:
            - StripPrefix=1

        - id: document_service_rest
          uri: lb://DOCUMENT-SERVICE # <-- Dynamic lookup via Eureka!
          predicates:
            - Path=/document/**

        - id: customers_service_mcp
          uri: lb://CUSTOMERS-SERVICE
          predicates:
            - Path=/customers/mcp/**
#          filters:
#            - StripPrefix=1 # Removes '/customer' so the service just intercepts '/mcp'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true # <--- ADD THIS
#      # Alternatively, you can force it to use localhost:
#      # hostname: localhost